//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SOEDUEntities : DbContext
    {
        public SOEDUEntities()
            : base("name=SOEDUEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_Assess> Sys_Assess { get; set; }
        public virtual DbSet<Sys_Attach> Sys_Attach { get; set; }
        public virtual DbSet<Sys_Course> Sys_Course { get; set; }
        public virtual DbSet<Sys_CourseCategory> Sys_CourseCategory { get; set; }
        public virtual DbSet<Sys_Lesson> Sys_Lesson { get; set; }
        public virtual DbSet<Sys_Section> Sys_Section { get; set; }
        public virtual DbSet<Sys_StudentCourse> Sys_StudentCourse { get; set; }
        public virtual DbSet<Sys_StudentTest> Sys_StudentTest { get; set; }
        public virtual DbSet<Sys_StudentTestSection> Sys_StudentTestSection { get; set; }
        public virtual DbSet<Sys_Target> Sys_Target { get; set; }
        public virtual DbSet<Sys_TeacherCourse> Sys_TeacherCourse { get; set; }
        public virtual DbSet<Sys_Test> Sys_Test { get; set; }
        public virtual DbSet<Sys_TestLesson> Sys_TestLesson { get; set; }
        public virtual DbSet<Sys_TestLessonAnswer> Sys_TestLessonAnswer { get; set; }
        public virtual DbSet<Sys_TestLessonQuestion> Sys_TestLessonQuestion { get; set; }
        public virtual DbSet<Sys_TestSection> Sys_TestSection { get; set; }
        public virtual DbSet<Sys_TestSectionAnswer> Sys_TestSectionAnswer { get; set; }
        public virtual DbSet<Sys_TestSectionQuestion> Sys_TestSectionQuestion { get; set; }
        public virtual DbSet<Sys_Users> Sys_Users { get; set; }
    }
}
