//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_TestLessonAnswer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_TestLessonAnswer()
        {
            this.Sys_TestLessonQuestion = new HashSet<Sys_TestLessonQuestion>();
        }
    
        public string Answer_ID { get; set; }
        public string Test_ID { get; set; }
        public string Answer_Name { get; set; }
    
        public virtual Sys_Test Sys_Test { get; set; }
        public virtual Sys_TestLesson Sys_TestLesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_TestLessonQuestion> Sys_TestLessonQuestion { get; set; }
    }
}
