//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Course()
        {
            this.Sys_Assess = new HashSet<Sys_Assess>();
            this.Sys_Section = new HashSet<Sys_Section>();
            this.Sys_StudentCourse = new HashSet<Sys_StudentCourse>();
            this.Sys_Target = new HashSet<Sys_Target>();
            this.Sys_TeacherCourse = new HashSet<Sys_TeacherCourse>();
        }
    
        public string Course_ID { get; set; }
        public string Category_ID { get; set; }
        public string Course_Name { get; set; }
        public string Avatar { get; set; }
        public string Video { get; set; }
        public string VideoImg { get; set; }
        public bool IsYoutube { get; set; }
        public string Description { get; set; }
        public bool IsValue { get; set; }
        public Nullable<double> IsPrice { get; set; }
        public Nullable<double> IsPriceSale { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public bool Status { get; set; }
        public Nullable<int> IsOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Assess> Sys_Assess { get; set; }
        public virtual Sys_CourseCategory Sys_CourseCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Section> Sys_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_StudentCourse> Sys_StudentCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Target> Sys_Target { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_TeacherCourse> Sys_TeacherCourse { get; set; }
    }
}
