//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Users()
        {
            this.Sys_StudentCourse = new HashSet<Sys_StudentCourse>();
            this.Sys_StudentTest = new HashSet<Sys_StudentTest>();
            this.Sys_StudentTestSection = new HashSet<Sys_StudentTestSection>();
            this.Sys_Target = new HashSet<Sys_Target>();
            this.Sys_TeacherCourse = new HashSet<Sys_TeacherCourse>();
        }
    
        public string User_ID { get; set; }
        public string User_Name { get; set; }
        public string IsPassword { get; set; }
        public string IsName { get; set; }
        public Nullable<bool> IsSex { get; set; }
        public string IsAdds { get; set; }
        public string IsEmail { get; set; }
        public string IsMobile { get; set; }
        public string IsDes { get; set; }
        public string IsFoto { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public string IsLevel { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_StudentCourse> Sys_StudentCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_StudentTest> Sys_StudentTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_StudentTestSection> Sys_StudentTestSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Target> Sys_Target { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_TeacherCourse> Sys_TeacherCourse { get; set; }
    }
}
