//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Test()
        {
            this.Sys_StudentTest = new HashSet<Sys_StudentTest>();
            this.Sys_TestLessonAnswer = new HashSet<Sys_TestLessonAnswer>();
        }
    
        public string Test_ID { get; set; }
        public string Lesson_ID { get; set; }
        public string Test_Name { get; set; }
        public string IsSetTime { get; set; }
    
        public virtual Sys_Lesson Sys_Lesson { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_StudentTest> Sys_StudentTest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_TestLessonAnswer> Sys_TestLessonAnswer { get; set; }
    }
}
