//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Target
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Target()
        {
            this.Sys_Target1 = new HashSet<Sys_Target>();
        }
    
        public string Target_ID { get; set; }
        public string Course_ID { get; set; }
        public string User_ID { get; set; }
        public string Parent_ID { get; set; }
        public Nullable<int> IsStar { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsOrder { get; set; }
    
        public virtual Sys_Course Sys_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Target> Sys_Target1 { get; set; }
        public virtual Sys_Target Sys_Target2 { get; set; }
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
