//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Lesson
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_Lesson()
        {
            this.Sys_Attach = new HashSet<Sys_Attach>();
            this.Sys_Lesson1 = new HashSet<Sys_Lesson>();
            this.Sys_Test = new HashSet<Sys_Test>();
        }
    
        public string Lesson_ID { get; set; }
        public string Section_ID { get; set; }
        public string Lesson_Name { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Video { get; set; }
        public string VideoImg { get; set; }
        public string ParentID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public Nullable<bool> IsStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Attach> Sys_Attach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Lesson> Sys_Lesson1 { get; set; }
        public virtual Sys_Lesson Sys_Lesson2 { get; set; }
        public virtual Sys_Section Sys_Section { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Test> Sys_Test { get; set; }
    }
}
