//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_StudentCourse
    {
        public string User_ID { get; set; }
        public string Course_ID { get; set; }
        public Nullable<bool> IsStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Sys_Course Sys_Course { get; set; }
        public virtual Sys_Users Sys_Users { get; set; }
    }
}
