//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_Attach
    {
        public string Attach_ID { get; set; }
        public string Lesson_ID { get; set; }
        public string File_Name { get; set; }
        public string Des { get; set; }
        public byte[] FileSource { get; set; }
        public string FileSize { get; set; }
        public Nullable<int> IsOrder { get; set; }
    
        public virtual Sys_Lesson Sys_Lesson { get; set; }
    }
}
