//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOEDU.Entities.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sys_CourseCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sys_CourseCategory()
        {
            this.Sys_Course = new HashSet<Sys_Course>();
            this.Sys_CourseCategory1 = new HashSet<Sys_CourseCategory>();
        }
    
        public string Category_ID { get; set; }
        public string Category_Name { get; set; }
        public string Title_Name { get; set; }
        public string IsIcon { get; set; }
        public Nullable<int> IsOrder { get; set; }
        public string Parent_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_Course> Sys_Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sys_CourseCategory> Sys_CourseCategory1 { get; set; }
        public virtual Sys_CourseCategory Sys_CourseCategory2 { get; set; }
    }
}
